TestApp03/Controllers/MedidaController.cs
using BLL;
using EML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestApp03.Controllers
{
    public class MedidaController : Controller
    {
        private MedidaBLL bll = new MedidaBLL();
        // GET: Medida
        public ActionResult Index()
        {
            ViewBag.TituloViewPanel = "Catalogo de Medidas";

            var ListaMedida = bll.ObtenerListaMedidas();
            return View(ListaMedida);
        }

        public ActionResult Editar(int Id)
        {
            ViewBag.TituloViewPanel = "Editar Medida";
            var Medida = bll.ObtenerMedida(Id);
            return View(Medida);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Medida model)
        {
            ViewBag.TituloViewPanel = "Editar Medida";
            if (ModelState.IsValid)
            {
                bll.ActualizarMedida(model);
            }

            return RedirectToAction("Index");

        }

        public ActionResult Crear()
        {
            ViewBag.TituloViewPanel = "Crear Medida";
            Medida model = new Medida();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Medida model)
        {
            ViewBag.TituloViewPanel = "Crear Medida";
            if (ModelState.IsValid)
            {
                bll.AgregarMedida(model);
            }

            return RedirectToAction("Index");
        }
    }
}

TestApp03/Controllers/ProductoController.cs
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestApp03.Models.Producto;

namespace TestApp03.Controllers
{
    public class ProductoController : Controller
    {
        private ProductoBLL productobll = new ProductoBLL();
        private CategoriaBLL categoriasbll = new CategoriaBLL();
        private MedidaBLL medidasbll = new MedidaBLL();
        private ProveedorBLL proveedoresbll = new ProveedorBLL();
        // GET: Producto
        public ActionResult Index()
        {
            var ListaProducto = productobll.ObtenerListaProductos();
            return View(ListaProducto);
        }

        public ActionResult Editar(int Id)
        {
            ProductoAddEditViewModel model = (ProductoAddEditViewModel) productobll.ObtenerProducto(Id);
            model.Proveedores = this.ObtenerProveedores();
            model.Categorias = this.ObtenerCategorias();
            model.Medidas = this.ObtenerMedidas();

            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(ProductoAddEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                productobll.ActualizarProducto(model);
                return RedirectToAction("Index");

            }
            else
            {
                model.Proveedores = this.ObtenerProveedores();
                model.Categorias = this.ObtenerCategorias();
                model.Medidas = this.ObtenerMedidas();
                return View(model);

            }


        }

        public ActionResult Crear()
        {
            ProductoAddEditViewModel model = new ProductoAddEditViewModel();
            model.Proveedores = this.ObtenerProveedores();
            model.Categorias = this.ObtenerCategorias();
            model.Medidas = this.ObtenerMedidas();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(ProductoAddEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                productobll.AgregarProducto(model);
                return RedirectToAction("Index");
            }
            else
            {
                model.Proveedores = this.ObtenerProveedores();
                model.Categorias = this.ObtenerCategorias();
                model.Medidas = this.ObtenerMedidas();
                return View(model);

            }

            
        }

        public IEnumerable<SelectListItem> ObtenerCategorias()
        {
            var a = categoriasbll.ObtenerListaCategorias().Select(x => new SelectListItem
            {
                Value = x.CategoriaId.ToString(),
                Text = x.Nombre
            }).ToList();

            a.Insert(0, new SelectListItem { Value = null, Text = "--- Seleccione una Categoria ---" });
            return new SelectList(a,"Value","Text");
        }

        public IEnumerable<SelectListItem> ObtenerProveedores()
        {
            var a = proveedoresbll.ObtenerListaProveedors().Select(x => new SelectListItem
            {
                Value = x.ProveedorId.ToString(),
                Text = x.Nombre
            }).ToList();

            a.Insert(0, new SelectListItem { Value = null, Text = "--- Seleccione una Proveedor ---" });
            return new SelectList(a, "Value", "Text");
        }

        public IEnumerable<SelectListItem> ObtenerMedidas()
        {
            var a = medidasbll.ObtenerListaMedidas().Select(x => new SelectListItem
            {
                Value = x.MedidaId.ToString(),
                Text = x.Nombre
            }).ToList();

            a.Insert(0, new SelectListItem { Value = null, Text = "--- Seleccione una Medida ---" });
            return new SelectList(a, "Value", "Text");
        }


    }
}

TestApp03/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using EML;
namespace TestApp03.Controllers
{
    public class ProveedorController : Controller
    {
        private ProveedorBLL bll = new ProveedorBLL();
        // GET: Proveedor
        public ActionResult Index()
        {
            var ListaProveedor = bll.ObtenerListaProveedors();
            return View(ListaProveedor);
        }

        public ActionResult Editar(int Id)
        {
            var Proveedor = bll.ObtenerProveedor(Id);
            return View(Proveedor);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Proveedor model)
        {
            if (ModelState.IsValid)
            {
                bll.ActualizarProveedor(model);
            }

            return RedirectToAction("Index");

        }

        public ActionResult Crear()
        {
            Proveedor model = new Proveedor();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Proveedor model)
        {
            if (ModelState.IsValid)
            {
                bll.AgregarProveedor(model);
            }

            return RedirectToAction("Index");
        }
    }
}

TestApp03/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Test</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/FontAwesome")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Start Bootstrap
                    </a>
                </li>
                <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                <li>@Html.ActionLink("Categoria", "Index", "Categoria")</li>
                <li>@Html.ActionLink("Proveedores", "Index", "Proveedor")</li>
                <li>@Html.ActionLink("Medidas", "Index", "Medida")</li>
                <li>@Html.ActionLink("Productos", "Index", "Producto")</li>
                <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">

                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">
                                <a href="#menu-toggle" class="btn btn-default" id="menu-toggle" aria-label="Menú">
                                    <i class="fa fa-bars" aria-hidden="true"></i>
                                </a>
                            </a>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <div class="btn-group open">
                                    <a class="btn btn-primary" href="#"><i class="fa fa-user fa-fw"></i> User</a>
                                    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                                        <span class="fa fa-caret-down" title="Toggle dropdown menu"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#"><i class="fa fa-pencil fa-fw"></i> Edit</a></li>
                                        <li><a href="#"><i class="fa fa-trash-o fa-fw"></i> Delete</a></li>
                                        <li><a href="#"><i class="fa fa-ban fa-fw"></i> Ban</a></li>
                                        <li class="divider"></li>
                                        <li><a href="#"><i class="fa fa-unlock"></i> Make admin</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">@ViewBag.TituloViewPanel</div>
                            <div class="panel-body">@RenderBody()</div>
                        </div>

                        
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/App")

    @RenderSection("scripts", required: false)
</body>
</html>