TestApp03/Models/Producto/ProductoAddEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EML;

namespace TestApp03.Models.Producto
{
    public class ProductoAddEditViewModel : EML.Producto
    {
        public IEnumerable<SelectListItem> Proveedores { get; set; }
        public IEnumerable<SelectListItem> Categorias { get; set; }
        public IEnumerable<SelectListItem> Medidas { get; set; }
    }
}

TestApp03/Controllers/ImagenProductoController.cs
using BLL;
using EML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestApp03.Models.ImagenProducto;

namespace TestApp03.Controllers
{
    public class ImagenProductoController : Controller
    {
        private ImagenProductoBLL bll = new ImagenProductoBLL();
        // GET: ImagenProducto
        public ActionResult Index(int id)
        {
            ViewBag.TituloViewPanel = "Carga de Imagenes";

            ImagenProductoViewModel model = new ImagenProductoViewModel();
            model.ProductoId = id;
            model.ListaImagenes = bll.ObtenerImagenesPorProducto(id);
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ImagenProductoViewModel model)
        {
            ViewBag.TituloViewPanel = "Carga de Imagenes";

            // Initialization.  
            string fileContent = string.Empty;
            string fileContentType = string.Empty;

            try
            {
                // Verification  
                if (ModelState.IsValid)
                {
                    // Converting to bytes.  
                    byte[] uploadedFile = new byte[model.FileAttach.InputStream.Length];
                    model.FileAttach.InputStream.Read(uploadedFile, 0, uploadedFile.Length);

                    // Initialization.  
                    fileContent = Convert.ToBase64String(uploadedFile);
                    fileContentType = model.FileAttach.ContentType;

                    // Saving info.  
                    ImagenProducto img = new ImagenProducto();
                    img.ProductoId = model.ProductoId;
                    img.file_name = model.FileAttach.FileName;
                    img.file_ext = fileContentType;
                    img.file_base64 = fileContent;
                    img.description = model.Descripcion ?? img.file_name;
                    img.IsPrincipal = model.IsPrincipal;
                    var a = bll.AgregarImagenPorProducto(img);
                    
                }

                // Settings.  
                model.ListaImagenes = bll.ObtenerImagenesPorProducto(model.ProductoId);
            }
            catch (Exception ex)
            {
                // Info  
                Console.Write(ex);
            }

            // Info  
            return this.View(model);
        }

        public ActionResult DownloadFile(int fileId)
        {
            // Model binding.  
            ImagenProductoViewModel model = new ImagenProductoViewModel { FileAttach = null,ListaImagenes = new List<ImagenProducto>() };

            try
            {
                // Loading dile info.  
                var fileInfo = bll.ObtenerDetalleImagenPorProducto(fileId);

                // Info.  
                return this.GetFile(fileInfo.file_base64, fileInfo.file_ext);
            }
            catch (Exception ex)
            {
                // Info  
                Console.Write(ex);
            }

            // Info.  
            return this.View(model);
        }

        private FileResult GetFile(string fileContent, string fileContentType)
        {
            // Initialization.  
            FileResult file = null;

            try
            {
                // Get file.  
                byte[] byteContent = Convert.FromBase64String(fileContent);
                file = this.File(byteContent, fileContentType);
            }
            catch (Exception ex)
            {
                // Info.  
                throw ex;
            }

            // info.  
            return file;
        }
    }
}

TestApp03/Controllers/ProductoController.cs
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestApp03.Models.Producto;

namespace TestApp03.Controllers
{
    public class ProductoController : Controller
    {
        private ProductoBLL productobll = new ProductoBLL();
        private CategoriaBLL categoriasbll = new CategoriaBLL();
        private MedidaBLL medidasbll = new MedidaBLL();
        private ProveedorBLL proveedoresbll = new ProveedorBLL();
        // GET: Producto
        public ActionResult Index()
        {
            var ListaProducto = productobll.ObtenerListaProductos();
            return View(ListaProducto);
        }

        public ActionResult Editar(int Id)
        {
            ProductoAddEditViewModel model = (ProductoAddEditViewModel) productobll.ObtenerProducto(Id);
            model.Proveedores = this.ObtenerProveedores();
            model.Categorias = this.ObtenerCategorias();
            model.Medidas = this.ObtenerMedidas();

            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(ProductoAddEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                productobll.ActualizarProducto(model);
                return RedirectToAction("Index");

            }
            else
            {
                model.Proveedores = this.ObtenerProveedores();
                model.Categorias = this.ObtenerCategorias();
                model.Medidas = this.ObtenerMedidas();
                return View(model);

            }


        }

        public ActionResult Crear()
        {
            ProductoAddEditViewModel model = new ProductoAddEditViewModel();
            model.Proveedores = this.ObtenerProveedores();
            model.Categorias = this.ObtenerCategorias();
            model.Medidas = this.ObtenerMedidas();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(ProductoAddEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                productobll.AgregarProducto(model);
                return RedirectToAction("Index");
            }
            else
            {
                model.Proveedores = this.ObtenerProveedores();
                model.Categorias = this.ObtenerCategorias();
                model.Medidas = this.ObtenerMedidas();
                return View(model);

            }

            
        }

        public IEnumerable<SelectListItem> ObtenerCategorias()
        {
            var a = categoriasbll.ObtenerListaCategorias().Select(x => new SelectListItem
            {
                Value = x.CategoriaId.ToString(),
                Text = x.Nombre
            }).ToList();

            a.Insert(0, new SelectListItem { Value = null, Text = "--- Seleccione una Categoria ---" });
            return new SelectList(a,"Value","Text");
        }

        public IEnumerable<SelectListItem> ObtenerProveedores()
        {
            var a = proveedoresbll.ObtenerListaProveedors().Select(x => new SelectListItem
            {
                Value = x.ProveedorId.ToString(),
                Text = x.Nombre
            }).ToList();

            a.Insert(0, new SelectListItem { Value = null, Text = "--- Seleccione una Proveedor ---" });
            return new SelectList(a, "Value", "Text");
        }

        public IEnumerable<SelectListItem> ObtenerMedidas()
        {
            var a = medidasbll.ObtenerListaMedidas().Select(x => new SelectListItem
            {
                Value = x.MedidaId.ToString(),
                Text = x.Nombre
            }).ToList();

            a.Insert(0, new SelectListItem { Value = null, Text = "--- Seleccione una Medida ---" });
            return new SelectList(a, "Value", "Text");
        }


    }
}

TestApp03/Views/Producto/Crear.cshtml
@model TestApp03.Models.Producto.ProductoAddEditViewModel

@{
    ViewBag.Title = "Crear";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductoAddEditViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.CategoriaId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(x => Model.CategoriaId, new SelectList(Model.Categorias, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "CategoriaId" })

                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProveedorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProveedorId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(x => Model.ProveedorId, new SelectList(Model.Proveedores, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "ProveedorId" })

                @Html.ValidationMessageFor(model => model.ProveedorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MedidaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.MedidaId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(x => Model.MedidaId, new SelectList(Model.Medidas, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "MedidaId" })
                @Html.ValidationMessageFor(model => model.MedidaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionLarga, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescripcionLarga, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripcionLarga, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Existencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Existencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Existencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista de Productos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestApp03/Views/Producto/Editar.cshtml
@model TestApp03.Models.Producto.ProductoAddEditViewModel

@{
    ViewBag.Title = "Editar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductoAddEditViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductoId)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.CategoriaId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(x => Model.Categorias, new SelectList(Model.Categorias, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "CategoriaId" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProveedorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProveedorId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(x => Model.Proveedores, new SelectList(Model.Proveedores, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "ProveedorId" })
                @Html.ValidationMessageFor(model => model.ProveedorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MedidaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.MedidaId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(x => Model.Medidas, new SelectList(Model.Medidas, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "MedidaId" })
                @Html.ValidationMessageFor(model => model.MedidaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionLarga, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescripcionLarga, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripcionLarga, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Existencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Existencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Existencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestApp03/Views/Producto/Index.cshtml
@model IEnumerable<EML.Producto>

@{
    ViewBag.Title = "Index";
}

<p>
    @Html.ActionLink("Crear Producto", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoriaId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProveedorId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedidaId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DescripcionLarga)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Existencia)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategoriaId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProveedorId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MedidaId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DescripcionLarga)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Existencia)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id = item.ProductoId }) |
            @Html.ActionLink("Imagenes", "Index","ImagenProducto", new { id = item.ProductoId },null) |
            @*@Html.ActionLink("Details", "Details", new { id=item.ProductoId }) |
        @Html.ActionLink("Delete", "Delete", new { id=item.ProductoId })*@
        </td>
    </tr>
}

</table>